import org.gradle.api.initialization.resolve.RepositoriesMode

pluginManagement {
    repositories.clear()
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        maven {
            name = "TencentAuthority"
            url = uri("https://mirrors.tencent.com/repository/maven-tencent")
            metadataSources {
                gradleMetadata()
                mavenPom()
                artifact()
            }
        }
    }
}

rootProject.name = "task141-coroutines-test-authority-resolver"
